import re
import json

with open('js/exercises.js', 'r', encoding='utf-8') as f:
    content = f.read()

additions = {
    8013: " Tra l'altro, stasera ho deciso di preparare con cura tutti i vestiti per domani, così non farò tardi. Spero davvero di poter sedere di nuovo vicino a Matteo e di iniziare a capire meglio il francese, che mi sembra un po' difficile. Chissà quante altre sorprese mi riserverà questa incredibile scuola media!",
    8014: " Spero davvero che i nostri genitori mantengano la promessa di farci trascorrere le vacanze di Natale insieme in montagna. Non vedo l'ora di sfidarti a palle di neve e di scendere in slittino con te. Sarebbe il regalo di Natale più bello del mondo! Ricordati di scrivermi, mi manchi molto.",
}

# 8015: Perché fare sport è importante per i giovani (Testo Argomentativo, Facile) - current 284 -> needs 350
additions[8015] = " \\n\\nInoltre, praticare sport regolarmente aiuta a prevenire molte malattie legate a uno stile di vita troppo sedentario, come l'obesità e i problemi cardiovascolari, che purtroppo sono sempre più comuni tra i ragazzi di oggi a causa del tempo eccessivo trascorso davanti a schermi, videogiochi e telefoni cellulari. Una bella corsa nel parco o una partita di calcio all'aperto permettono di respirare aria fresca, di assorbire vitamina D grazie alla luce del sole e di rafforzare il sistema immunitario, rendendo il nostro corpo forte come una roccia e pronto a combattere i malanni invernali.\\n\\nC'è poi un altro aspetto fondamentale da non sottovalutare: lo sport è una vera e propria palestra di vita, che insegna a gestire lo stress, le emozioni negative e le frustrazioni. Quando si perde una partita importante o si sbaglia un rigore decisivo, si impara ad accettare la sconfitta con maturità, a non arrendersi mai di fronte alle difficoltà e a rialzarsi sempre con più grinta di prima. Il famoso detto 'l'importante non è vincere, ma partecipare' racchiude una grande verità: il vero successo non sta solo nella medaglia d'oro che si porta al collo, ma nel coraggio, nella dedizione e nell'impegno che si mettono in ogni allenamento quotidiano.\\n\\nInfine, lo sport è un modo meraviglioso per esplorare i propri talenti nascosti e per scoprire nuove passioni. C'è chi scopre di essere un nuotatore provetto, chi si innamora della danza classica, chi trova la sua strada nel judo o nella ginnastica ritmica. Ogni disciplina ha le sue regole, la sua bellezza e il suo fascino unico. Insomma, lo sport fa bene al cuore, al corpo e alla mente. Tutti dovrebbero trovare l'attività fisica più adatta ai propri gusti e farla diventare una sana e gioiosa abitudine quotidiana!"

# 8016: La grande estate di Giulio (Romanzo di formazione, Facile) - current 353 -> needs 280
additions[8016] = " \\n\\nLe giornate passavano in un lampo, scandite da tuffi mozzafiato dagli scogli, esplorazioni in grotte segrete popolate da piccoli granchi e lunghe passeggiate in bicicletta lungo i sentieri costieri, dove il profumo dei pini marittimi si mescolava a quello salmastro del mare. Un pomeriggio, mentre cercavano conchiglie su una spiaggia deserta, Giulio e i suoi amici si imbatterono in una vecchia barca a remi mezza sepolta dalla sabbia. Decisero che quella sarebbe stata la loro 'nave pirata' segreta, e passarono ore a dipingerla e ripararla con vecchie assi di legno trovate sulla riva.\\n\\nIn quella meravigliosa estate, Giulio non imparò solo a nuotare o a riparare barche. Imparò anche a fidarsi degli altri, a superare le proprie paure e a capire l'importanza della collaborazione. Quando il suo amico Leo si ferì accidentalmente al ginocchio cadendo dagli scogli, Giulio non scappò via per lo spavento, ma mantenne la calma, fasciando la ferita con la sua maglietta e correndo a cercare aiuto. Quell'episodio lo fece sentire improvvisamente più grande, più responsabile, come se avesse fatto un salto in avanti verso l'età adulta.\\n\\nQuando arrivò settembre, l'aria cominciò a rinfrescarsi e il momento dei saluti si avvicinò. Salutare la zia, gli amici e il mare non fu facile. Mentre guardava dal finestrino del treno la costa che si allontanava, Giulio sentì un pizzico di malinconia, ma sapeva che quella vacanza lo aveva cambiato per sempre. Non era più il ragazzino timido e solitario di giugno; era diventato un ragazzo forte, sicuro di sé e pieno di ricordi indimenticabili. La grande estate gli aveva regalato molto più di una semplice abbronzatura: gli aveva donato il coraggio di affrontare il mondo e la certezza che, ovunque andasse, l'amicizia vera non lo avrebbe mai abbandonato."

# 8017: I pensieri segreti di Leo (Romanzo psicologico, Facile) - current 344 -> needs 300
additions[8017] = " \\n\\nQuesto nuovo approccio lo aiutò incredibilmente durante le interrogazioni di storia, che prima erano il suo più grande incubo. Invece di concentrarsi sulla paura di sbagliare o di essere giudicato dai compagni, Leo iniziò a immaginare di essere lui stesso un protagonista degli eventi storici che stava raccontando. Immaginava di cavalcare al fianco di antichi guerrieri, di navigare su grandi navi esploratrici o di passeggiare per le strade dell'antica Roma. La storia divenne così una grande avventura, e la sua voce non tremava più.\\n\\nAnche a casa, Leo iniziò ad applicare questo nuovo modo di pensare. Quando i suoi genitori discutevano o c'erano momenti di tensione in famiglia, si ritirava in camera sua, prendeva un foglio bianco e iniziava a scrivere o a disegnare. Dipingeva le sue emozioni usando i colori: il rosso brillante per la rabbia improvvisa, il blu scuro per i momenti di tristezza, il giallo luminoso per la gioia e la speranza. Quei disegni divennero un vero e proprio specchio della sua anima, aiutandolo a comprendere meglio se stesso.\\n\\nUn giorno, prese la decisione coraggiosa di mostrare uno dei suoi disegni al professore di arte. Il professore rimase profondamente colpito dalla profondità e dall'intensità di quel lavoro, e propose a Leo di partecipare a un concorso scolastico di pittura. All'inizio il ragazzo fu assalito dal solito panico, ma poi si ricordò del suggerimento della madre. Respirò profondamente e decise di accettare la sfida. Che vincesse o perdesse, non importava: ciò che contava era aver trovato una voce, un modo unico e personale per esprimere i suoi pensieri segreti al mondo intero. Leo capì finalmente che la vera forza non sta nel non avere mai paura, ma nel trovare il coraggio di affrontarla un passo alla volta."

# 8018: Un nuovo inizio per Samir (Romanzo sociale, Facile) - current 296 -> needs 340
additions[8018] = " \\n\\nIl torneo di fine anno scolastico divenne l'evento più atteso da tutta la classe. La squadra di Samir si allenava duramente ogni pomeriggio nel parchetto vicino alla scuola. Samir non era solo un bravo giocatore, ma dimostrò di avere anche la stoffa del vero capitano: incoraggiava i compagni che sbagliavano, dava preziosi consigli tecnici e non si arrabbiava mai. Durante la finale del torneo contro la squadra della sezione C, la partita fu molto combattuta e tesa. A pochi minuti dalla fine, il punteggio era in perfetta parità. Fu allora che Samir, con uno scatto fulmineo, rubò la palla agli avversari, dribblò due difensori e, con un passaggio smarcante perfetto, permise al suo compagno Marco di segnare il gol della vittoria. La squadra esultò, abbracciandosi e saltando di gioia.\\n\\nQuella vittoria fu magica. Non fu solo una vittoria sportiva, ma un trionfo umano che andava oltre il semplice risultato. I genitori dei compagni di squadra di Samir si avvicinarono alla sua famiglia, stringendo loro le mani e ringraziandoli. Per la prima volta dal loro arrivo in Italia, la famiglia di Samir fu invitata a cena a casa di un compagno di scuola. Quella sera, seduti intorno a una grande tavola imbandita, mangiarono cibi italiani mescolati a dolci tipici portati dalla madre di Samir, ridendo e raccontandosi storie fino a tardi.\\n\\nSamir guardò i suoi genitori sorridere sereni e capì una cosa fondamentale: l'integrazione non si ottiene da un giorno all'altro, ma si costruisce con piccoli gesti di apertura, pazienza e rispetto reciproco. Il pallone gli aveva offerto un linguaggio universale, ma era stato il suo cuore aperto a fare il resto. Ora Samir sapeva che, anche se l'Italia non era il paese in cui era nato, poteva davvero diventare la sua vera casa, un luogo dove poter crescere felice e realizzare tutti i suoi sogni per il futuro."

# 8019: Marco e il mistero del Colosseo (Romanzo storico, Facile) - current 280 -> needs 350
additions[8019] = " \\n\\nIl giorno dei giochi inaugurali, Roma sembrava in festa. Fin dalle prime luci dell'alba, migliaia di cittadini romani di ogni classe sociale si affollarono verso le grandi entrate dell'anfiteatro, vestiti con tuniche colorate e pieni di aspettativa. Marco, nascosto vicino a una delle porte secondarie destinate ai gladiatori, osservava tutto con occhi sgranati e il cuore che batteva all'impazzata. Poteva sentire il ruggito dei leoni affamati chiusi nelle gabbie sotterranee, il rumore metallico delle spade che venivano affilate e le grida di eccitazione della folla che prendeva posto sugli spalti di marmo bianco.\\n\\nImprovvisamente, Marco vide qualcosa di molto sospetto. Un uomo incappucciato stava versando una strana polvere scura nella ciotola d'acqua destinata al gladiatore più forte e valoroso di tutta Roma, il gigantesco Tito. Marco sapeva che Tito era l'idolo della folla e che molti scommettitori disonesti volevano vederlo perdere per arricchirsi ingiustamente. Senza pensarci due volte, il coraggioso ragazzino strisciò silenziosamente tra le ombre dei corridoi, aspettò che l'uomo misterioso si allontanasse e, con un calcio deciso, rovesciò la ciotola avvelenata per terra, salvando la vita al campione.\\n\\nQuando Tito scoprì cosa era successo, prese Marco sotto la sua grande ala protettiva. Per ringraziarlo, il gladiatore permise al ragazzo di assistere ai combattimenti da una posizione privilegiata e sicura. Quella giornata fu indimenticabile per Marco: vide lotte epiche, belve feroci provenienti da paesi lontanissimi e l'imperatore stesso che salutava il suo popolo soddisfatto. Marco tornò a casa la sera stanco ma immensamente felice. Aveva non solo realizzato il suo sogno di vedere il Colosseo, ma aveva anche contribuito a mantenere la giustizia e l'onore all'interno dell'arena. Da quel giorno, decise che da grande non sarebbe diventato un venditore del mercato, ma un vero soldato romano, pronto a difendere l'impero e i suoi valori di coraggio e lealtà."

def expand_texts():
    global content
    for id_val, addition in additions.items():
        pattern = r'("id": ' + str(id_val) + r',.*?"text": ")(.*?)(")'
        match = re.search(pattern, content, re.DOTALL)
        if match:
            old_text = match.group(2)
            new_text = old_text + addition
            full_old = match.group(0)
            full_new = match.group(1) + new_text + match.group(3)
            content = content.replace(full_old, full_new)
        else:
            print(f"Could not find ID {id_val}")
            
expand_texts()

with open('js/exercises.js', 'w', encoding='utf-8') as f:
    f.write(content)
print("Updated texts successfully.")
