import re

with open('js/exercises.js', 'r', encoding='utf-8') as f:
    content = f.read()

additions = {
    8028: " Quelle giornate li resero più forti e più consapevoli del fatto che la vita è un dono immenso.",
    8029: " Gli scacchi, infatti, non sono solo una sfida per vincere a tutti i costi, ma una nobile palestra per allenare costantemente la nostra preziosa intelligenza e per forgiare il carattere con pazienza e rispetto profondo dell'avversario.",
    8030: " Dobbiamo quindi proteggere le specie animali e vegetali che abitano oggi il nostro fragile mondo per evitare nuovi disastri.",
    8031: " I fiorentini ne sono orgogliosi, sapendo di vivere in un posto meravigliosamente unico sotto il cielo azzurro toscano.",
    8032: " Questo ci fa capire che la mente umana possiede una forza evocativa sconfinata, capace di superare ogni barriera. Nonostante la sua infinita malinconia, Giacomo Leopardi ci regala qui una potentissima affermazione della vitalità del pensiero, spingendoci a sognare sempre oltre la siepe delle nostre paure terrene.",
    8033: " Qualche giorno dopo, la famiglia di Marco fece ristrutturare l'intera biblioteca e vi aggiunse un bellissimo camino in pietra. Il dipinto fu donato a un museo locale affinché tutti potessero ammirarne i dettagli paesaggistici senza conoscere il suo oscuro segreto. Di notte, quando fuori piove e i tuoni rimbombano nel cielo oscuro, Marco si siede ancora sulla vecchia poltrona di pelle, ascoltando il rumore della pioggia e sorridendo pensando a come, con coraggio e determinazione, avesse regalato la libertà a uno spirito triste, sconfiggendo una leggenda spaventosa con la sola arma della verità storica.",
    8034: " Gli anni passarono ed Elia divenne un uomo adulto, ma non riuscì mai a dimenticare completamente quella spaventosa notte infantile. A volte, nei suoi peggiori incubi notturni, sentiva ancora la presa gelida di quella piccola mano di porcellana che cercava di trascinarlo nell'oscurità più profonda. Quel ricordo gli insegnò a non sfidare mai i segreti sepolti nel buio e a rispettare le paure irrazionali che tutti noi portiamo nascoste in fondo al cuore.",
    8035: " Questa divertente disavventura insegnò al signor Bianchi che la pasticceria poteva riservare sorprese ben più emozionanti dei soliti clienti. Decise persino di dedicare una nuova torta speciale a Tommaso e al suo pappagallo: si chiamò 'La Nuvola Bianca', una sofficissima torta ripiena di panna fresca, scaglie di cioccolato e pezzetti di ananas, che divenne rapidamente il dolce più venduto e amato di tutto il quartiere, facendo la felicità dei grandi e soprattutto dei più piccini.",
    8036: " Da quel giorno memorabile, l'aspirapolvere intelligente venne riprogrammato per limitarsi a svolgere i suoi semplici compiti di pulizia, e il giovane hacker di famiglia ricevette una lauta ricompensa per il suo prezioso e coraggioso intervento tecnico. Certo, ogni tanto, mentre guarda i vecchi film di fantascienza, il signor Rossi lancia ancora un'occhiata sospettosa al tostapane e al frullatore in cucina, temendo che possano aver imparato qualcosa dal loro amico robotico, ma per fortuna, tutto sembra essere tornato alla normale e tranquilla routine domestica.",
    8037: " Viaggiare insegna davvero molte più cose di mille libri di geografia studiati a memoria sui banchi di scuola. Ti fa crescere, ti apre la mente e ti costringe ad affrontare i problemi reali con prontezza di spirito e fantasia. Questa mia prima piccola grande odissea in treno sarà solo l'inizio di innumerevoli altre esplorazioni in giro per l'Italia e per il mondo, sempre alla ricerca di nuove emozioni e amicizie indimenticabili. Viaggerò sempre leggero, ma con il cuore colmo di sogni enormi e speranze infinite.",
    8038: " Spero che tu non smetta mai di scrivere con la stessa immensa sensibilità e poesia che ti contraddistingue, perché per ragazze come me le tue parole sono veri e propri salvagenti in mezzo al mare in tempesta della gioventù. La tua arte ha il grandissimo potere di unire le persone e di farle sentire meno sole, in un mondo che a volte sembra scorrere troppo in fretta e dimenticarsi di ascoltare i nostri sentimenti più profondi e delicati. Grazie per avermi salvata e avermi fatto riscoprire la bellezza di sognare in grande.",
    8039: " In ultima analisi, dobbiamo smettere di etichettare la tecnologia in modo semplicistico e binario come puramente buona o puramente cattiva. I videogiochi sono un vasto mare di possibilità creative, e sta a noi imparare a navigare con saggezza tra le sue correnti, sfruttando al massimo le correnti positive ed evitando con astuzia gli scogli pericolosi dell'isolamento e della dipendenza. Il vero traguardo è riuscire a bilanciare le epiche vittorie nei mondi digitali con i piccoli, preziosi e altrettanto meravigliosi successi della vita di tutti i giorni.",
    8040: " Gli anni del liceo sono in fondo proprio questo: una palestra in cui alleniamo non solo il cervello, ma soprattutto il nostro cuore e la nostra capacità di resistere alle pressioni esterne senza mai smarrire la nostra vera e unica identità. Sofia imparò a volersi bene per i suoi pregi e per i suoi meravigliosi difetti, diventando una giovane donna molto più serena, libera e indipendente, finalmente pronta a conquistare il mondo a testa alta."
}

# 8041: Il labirinto emotivo di Matteo (Romanzo psicologico, Intermedio) - current 187 -> needs 420
additions[8041] = " \\n\\nQuesta rabbia scaturiva da un profondo senso di impotenza: i suoi genitori si stavano separando e Matteo si sentiva diviso a metà, proprio come la sua vecchia casa in cui ormai regnava un silenzio opprimente e freddo. Il suo rifiuto di aprirsi agli altri era un enorme e pesantissimo scudo protettivo, costruito giorno dopo giorno per evitare di farsi ferire ancora di più dalle persone a cui voleva bene.\\n\\nUn giorno, durante un'ora di educazione fisica particolarmente faticosa, l'insegnante, il professor Marini, notò il comportamento sfuggente del ragazzo. Invece di rimproverarlo per la sua scarsa partecipazione alla partita di pallavolo, si sedette accanto a lui sulla panchina di legno dello spogliatoio e, guardandolo dritto negli occhi, gli raccontò della sua stessa difficile adolescenza. 'Non puoi controllare i venti e le tempeste che sconvolgono il mare della vita', gli disse con una voce calma e rassicurante, 'ma puoi sempre imparare a orientare le tue vele per non farti affondare'.\\n\\nQuelle parole furono per Matteo come un faro luminoso e potente nella nebbia fitta dei suoi pensieri. Lentamente, iniziò ad abbassare le sue alte difese difensive. Iniziò a tenere un diario segreto dove sfogava la sua frustrazione usando le parole anziché i silenzi ostili, e accettò finalmente di frequentare un gruppo di supporto pomeridiano per ragazzi in difficoltà emotiva organizzato dalla scuola. Li, circondato da compagni che capivano perfettamente le sue sensazioni, Matteo scoprì che condividere le proprie debolezze non è un segno di codardia, ma un atto di estremo coraggio. Il suo labirinto emotivo iniziò finalmente a schiarirsi, permettendogli di ritrovare la pace interiore e di tornare a sorridere in modo genuino e spontaneo."

# 8042: La forza dell'amicizia oltre i pregiudizi (Romanzo sociale, Intermedio) - current 163 -> needs 450
additions[8042] = " \\n\\nAll'inizio, gli altri compagni di classe italiani li guardavano con molta diffidenza. Youssef non capiva bene la lingua, aveva abitudini alimentari diverse dalle loro e spesso, durante l'intervallo, rimaneva solo in un angolo del cortile scolastico a fissare il vuoto con gli occhi lucidi. Andrea, però, decise di superare il muro invisibile del pregiudizio. Si avvicinò a lui offrendogli metà del suo panino con il prosciutto, e da quel piccolo gesto nacque un'amicizia che cambiò per sempre le loro esistenze.\\n\\nAndrea insegnò a Youssef le regole difficili e complicate della grammatica italiana, mentre Youssef gli raccontava antiche storie di mercati colorati, profumi di spezie orientali e lunghi viaggi attraverso deserti silenziosi sotto un cielo di milioni di stelle luminose. I due diventarono inseparabili, dimostrando a tutti gli insegnanti e ai genitori che le differenze culturali non sono un ostacolo insormontabile, ma una meravigliosa opportunità per arricchire il proprio bagaglio di conoscenze umane.\\n\\nIl loro legame speciale fu messo alla prova alla fine dell'anno scolastico, quando Youssef rischiò seriamente di essere bocciato a causa dei suoi bassi voti in storia e geografia. Andrea, invece di abbandonarlo al suo destino, decise di studiare con lui tutti i pomeriggi nella grande biblioteca comunale. Prepararono riassunti schematizzati, mappe concettuali colorate e inventarono simpatiche filastrocche per ricordare le date importanti. L'impegno e la costanza furono ampiamente ripagati: Youssef riuscì a superare brillantemente gli esami orali davanti a tutta la commissione ammirata. Quell'estate, i due amici festeggiarono la promozione mangiando un grosso gelato al limone, consapevoli che il vero banco di prova della società moderna è l'integrazione e il rispetto reciproco delle diversità."

# 8043: La vita quotidiana in un castello medievale (Romanzo storico, Intermedio) - current 162 -> needs 450
additions[8043] = " \\n\\nLe stanze all'interno del mastio principale erano buie e mal riscaldate, illuminate fiocamente solo da grandi e fumosi caminetti di pietra e da piccole candele di sego che emanavano un odore acre e pungente. Durante i rigidissimi mesi invernali, il freddo penetrava fin nelle ossa degli abitanti, e l'unica consolazione per chi non era di nobili origini era radunarsi nella grande cucina, dove enormi focolari rimanevano perennemente accesi per arrostire cacciagione e preparare spesse zuppe di legumi per la truppa.\\n\\nIl castello non era abitato solo dai ricchi e potenti signori, ma era un vero e proprio micro-cosmo autosufficiente: vi vivevano fabbri robusti che battevano il ferro ardente sulle incudini rumorose, abili artigiani, servitori stanchi, guardie armate di pesanti alabarde e contadini che lavoravano incessantemente le terre circostanti per garantire le abbondanti scorte alimentari necessarie a superare i lunghi e temuti assedi militari. La vita di questi lavoratori era durissima, segnata dalla fatica nei campi fangosi e dal costante timore di epidemie fulminanti o improvvise incursioni barbariche.\\n\\nEppure, nonostante le asperità quotidiane e la netta e ingiusta divisione tra le rigide classi sociali, c'erano anche rari momenti di gioia collettiva. Durante le importanti festività religiose, il grande cortile centrale del castello si animava magicamente di colori vivaci, canti popolari ritmati, allegri giullari di corte e acrobati che intrattenevano la corte del signore e il popolo festante. Questi eventi spezzavano la dura monotonia del lavoro e offrivano l'illusione temporanea di un mondo più sereno e giusto. Studiare la dura vita nei castelli ci aiuta ad apprezzare le infinite comodità, i diritti e le sicurezze che abbiamo ereditato dal lungo e doloroso cammino della storia umana."

# 8044: Primi passi sulla colonia Marte Rosso (Fantascienza, Intermedio) - current 154 -> needs 450
additions[8044] = " \\n\\nAll'interno delle cupole di vetro ultra-resistente che proteggevano i coloni dalle letali radiazioni cosmiche e dalle tempeste di sabbia corrosiva, l'aria era un bene prezioso, purificato costantemente da enormi e rumorosi macchinari di riciclo chimico. Il cibo consisteva esclusivamente in speciali barrette proteiche sintetiche senza sapore e minuscole verdure idroponiche coltivate sotto potenti lampade ultraviolette. Ogni goccia d'acqua veniva religiosamente recuperata, persino il sudore corporeo, per essere filtrata e riutilizzata all'infinito per la sopravvivenza della comunità.\\n\\nUn giorno, durante un'esplorazione programmata in superficie a bordo dei pesanti rover corazzati, la giovane astrobiologa Elara scoprì qualcosa di straordinario e totalmente inaspettato: all'interno di una buia caverna ghiacciata situata vicino all'equatore marziano, trovò tracce fossili inconfutabili di batteri extraterrestri antichi di miliardi di anni. La notizia si diffuse a macchia d'olio nella colonia, riempiendo di immensa speranza e rinnovato entusiasmo i cuori stanchi dei ricercatori. Non erano più soli nell'universo, e forse un tempo Marte aveva ospitato oceani blu e foreste lussureggianti.\\n\\nQuesta incredibile scoperta spinse il consiglio direttivo della base ad accelerare i rivoluzionari progetti di 'terraformazione' del pianeta rosso. Se i batteri erano riusciti a sopravvivere nel sottosuolo ostile, forse la vita complessa poteva rinascere in futuro. Nonostante la grandissima nostalgia per i cieli azzurri, le piogge primaverili e i vasti oceani salati della lontana Madre Terra, i coraggiosi pionieri marziani sapevano che stavano compiendo il passo evolutivo più importante della millenaria storia umana, aprendo per sempre la via verso le stelle lontane."

# 8045: Nel magico mondo di Riflessia (Fantastico, Intermedio) - current 188 -> needs 420
additions[8045] = " \\n\\nUna mattina, mentre si specchiava distrattamente nelle acque cristalline del Grande Lago di Cristallo, notò che il suo riflesso non riproduceva esattamente i suoi movimenti. Invece di sorridere tristemente come lei, il riflesso sembrava cercare di comunicarle qualcosa di estremamente urgente, gesticolando freneticamente e puntando l'indice verso il centro scuro delle acque profonde. Incuriosita e un po' spaventata, Elara si sporse in avanti e finì per cadere, venendo inaspettatamente inghiottita da un magico portale subacqueo luminoso.\\n\\nSi ritrovò dall'altra parte dello specchio, in un mondo alla rovescia chiamato Antiriflessia. In questo strano e affascinante regno, il cielo era di un brillante arancione neon e gli alberi, al posto delle foglie, avevano grandi orologi d'oro che giravano all'indietro producendo un ticchettio ipnotico e rassicurante. Incontrò creature fantastiche, come farfalle parlanti con ali fatte di vetro colorato e saggi gufi giganti che leggevano i pensieri passati e futuri delle persone. Lì, Elara scoprì di essere la prescelta da un'antica profezia elfica, incaricata di riportare l'equilibrio magico tra i due mondi paralleli, rubato secoli prima dal perfido Re dell'Oblio, che si nutriva dei ricordi felici degli esseri umani.\\n\\nArmata solo di un prisma magico indistruttibile capace di deviare e amplificare i raggi di luce solare, Elara affrontò un lunghissimo e pericoloso viaggio verso il cupo Castello d'Ombra. Sfidando labirinti insidiosi e mostri fatti di nebbia tossica, riuscì finalmente a sconfiggere il tiranno illuminandolo con un fascio di luce purissima che lo trasformò in polvere stellare inoffensiva. Ritornata trionfalmente al suo villaggio originario di Riflessia, la principessa capì che la vera magia non risiede nei poteri sovrannaturali, ma nel grandissimo coraggio di scoprire se stessi, accettando le proprie ombre per far splendere appieno la propria luce interiore."

# 8046: La mia più grande sfida: Parlare in pubblico (Autobiografia, Intermedio) - current 171 -> needs 440
additions[8046] = " \\n\\nQuesto immenso terrore emotivo mi perseguitò per tutta la durata delle scuole superiori, limitando drasticamente le mie enormi potenzialità accademiche. Ogni volta che dovevo presentare un elaborato di fronte alla classe, le mani iniziavano a sudarmi freddo, le gambe mi tremavano violentemente come foglie al vento e la voce si riduceva a un timido sussurro incomprensibile. Nonostante prendessi sempre ottimi voti agli esami scritti grazie allo studio matto e disperatissimo, sapevo benissimo che nel mondo del lavoro moderno, saper comunicare in modo efficace le proprie idee è fondamentale quasi quanto avere ottime competenze tecniche.\\n\\nLa vera e propria svolta arrivò durante il mio secondo anno di studi universitari in Scienze della Comunicazione. Incoraggiato fortemente da un professore molto attento ed empatico, decisi di affrontare di petto il mio più grande e oscuro demone iscrivendomi volontariamente a un intenso corso di improvvisazione teatrale extracurriculare. Fu un'esperienza all'inizio totalmente traumatica e imbarazzante, ma col tempo imparai preziose tecniche per gestire l'ansia da palcoscenico: iniziai a focalizzarmi intensamente sul messaggio che volevo trasmettere e non sul giudizio spietato degli altri, capendo che l'uditorio non era un nemico pronto ad attaccarmi, ma un alleato curioso e interessato.\\n\\nIl giorno della mia discussione finale di laurea, la grande aula magna dell'università era gremita di parenti e professori molto severi. Quando presi in mano il microfono, il mio cuore batteva ancora forte nel petto, ma questa volta non era paura, era pura e semplice adrenalina positiva. Esposi la mia lunga tesi con inaspettata sicurezza, passione bruciante e chiarezza cristallina, ricevendo alla fine i complimenti vivissimi e inaspettati dell'intera rigida commissione esaminatrice. Quell'incredibile successo mi insegnò che le nostre paure più radicate sono in realtà come muri immaginari altissimi: sembrano invincibili e insormontabili, ma una volta che troviamo il coraggio di iniziare a scalarli, scopriamo con gioia che dall'altra parte si nasconde la nostra totale e meravigliosa libertà."

# 8047: Samantha Cristoforetti: Determinazione nello spazio (Biografia, Intermedio) - current 157 -> needs 450
additions[8047] = " \\n\\nFin da bambina, mentre osservava affascinata le costellazioni scintillanti dal piccolo e isolato paesino del Trentino in cui era cresciuta a contatto con la natura, Samantha sognava di poter esplorare l'universo sconfinato. Nonostante le mille difficoltà pratiche e i frequenti e fastidiosi pregiudizi nei confronti delle donne in ambito prettamente scientifico, tecnico e ingegneristico, non si è mai lasciata scoraggiare minimamente. Si è laureata brillantemente e con il massimo dei voti in ingegneria meccanica e aerospaziale in Germania, per poi intraprendere la durissima e selettiva carriera militare diventando uno dei migliori piloti caccia da combattimento dell'Aeronautica Militare Italiana, un ambiente fino a poco tempo prima riservato quasi esclusivamente agli uomini.\\n\\nLa sua immensa tenacia e preparazione l'hanno portata a superare brillantemente e senza sosta durissimi test fisici e psicologici per poter entrare nel prestigioso corpo degli astronauti dell'Agenzia Spaziale Europea (ESA). Nel celebre 2014, la missione spaziale Futura l'ha vista vivere e lavorare strenuamente a bordo della Stazione Spaziale Internazionale (ISS) per quasi 200 lunghi giorni, un record assoluto europeo di permanenza femminile nello spazio. Durante la sua delicatissima missione orbitale, Samantha ha condotto con grandissimo successo importanti esperimenti scientifici nel campo della medicina d'avanguardia, della fisica dei materiali complessi e ha persino testato speciali apparecchiature avanzate per stampanti 3D a gravità zero, utili per le future spedizioni umane verso il pianeta Marte.\\n\\nOltre alle sue enormi ed eccezionali doti prettamente tecniche e scientifiche, Samantha è molto amata e seguita sui social network mondiali per la sua semplicità disarmante e la sua voglia di condividere con entusiasmo la bellezza mozzafiato del pianeta Terra visto dall'immenso oblò della base orbitante. Le sue bellissime e frequentissime dirette video educative, spesso pensate per i giovani studenti in età scolare, l'hanno resa una vera e propria icona culturale ispiratrice. La sua straordinaria ed esemplare vita dimostra ampiamente a tutto il mondo che con lo studio approfondito, un'enorme determinazione ferrea e una sana passione, persino lo sconfinato e buio spazio interstellare può essere raggiunto a testa alta."

# 8048: Cronaca storica: 20 Luglio 1969, un passo da gigante (Cronaca, Intermedio) - current 157 -> needs 450
additions[8048] = " \\n\\nLa storica e pericolosissima missione dell'Apollo 11 era partita ben quattro giorni prima, sollevando enormi colonne di fuoco e fumo denso dal centro di comando americano di Cape Canaveral in Florida, spinta dalla mostruosa potenza dei mastodontici motori dell'enorme razzo Saturn V. A bordo, tre astronauti coraggiosissimi si preparavano ad affrontare il viaggio più audace, ignoto e letale dell'intera storia dell'umanità: Neil Armstrong, in qualità di comandante esperto, Edwin 'Buzz' Aldrin, il pilota infallibile del modulo lunare di discesa, e Michael Collins, rimasto stoicamente in orbita circolare da solo ad aspettarli a bordo del fondamentale modulo di comando in perenne rotazione.\\n\\nLa discesa del piccolo e fragile modulo 'Eagle' fu accompagnata da momenti di puro panico e tensione indescrivibile all'interno della centrale di controllo spaziale texana di Houston. Allarmi imprevisti dei vecchi computer di bordo e la drastica diminuzione del propellente costrinsero Armstrong a prendere immediatamente i comandi manuali, cercando con grandissima freddezza d'animo di evitare schianti catastrofici contro grossi crateri e massi spigolosi disseminati sulla superficie aliena. Quando la navicella toccò finalmente e delicatamente il suolo extraterrestre sollevando la celebre polvere grigia, in tutto il mondo un incredibile sospiro di sollievo collettivo si innalzò al cielo aperto.\\n\\nFu allora che Armstrong scese la rigida e metallica scaletta, pronunciando la famosissima e indimenticabile frase: 'Questo è un piccolo passo per un uomo, ma un gigantesco balzo per l'umanità'. Insieme ad Aldrin, condusse esperimenti scientifici molto complessi, installò un riflettore laser sofisticatissimo per misurare la distanza dalla Terra e, prima di ripartire trionfalmente, piantò simbolicamente e con orgoglio la bandiera degli Stati Uniti, lasciando per sempre le proprie inconfondibili orme impresse nell'eterna sabbia argentea e immobile del Mare della Tranquillità."

def expand_texts():
    global content
    for id_val, addition in additions.items():
        pattern = r'("id": ' + str(id_val) + r',.*?"text": ")(.*?)(")'
        match = re.search(pattern, content, re.DOTALL)
        if match:
            old_text = match.group(2)
            new_text = old_text + addition
            full_old = match.group(0)
            full_new = match.group(1) + new_text + match.group(3)
            content = content.replace(full_old, full_new)
        else:
            print(f"Could not find ID {id_val}")
            
expand_texts()

with open('js/exercises.js', 'w', encoding='utf-8') as f:
    f.write(content)
print("Updated texts successfully.")
