import re

with open('js/exercises.js', 'r', encoding='utf-8') as f:
    content = f.read()

additions = {
    8033: " Oltre a ritrovare la pace per sé e per i futuri abitanti della grande casa, quel coraggioso ragazzino aveva imparato l'inestimabile valore della curiosità e del coraggio.",
    8034: " D'altronde, certe porte dovrebbero rimanere per sempre chiuse a chiave.",
    8035: " Ed ecco che, da quel piccolo disastro causato da un uccellino impertinente, nacque un vero trionfo culinario senza precedenti.",
    8036: " La tecnologia, per quanto avanzata, ha ancora molto da imparare dall'essere umano.",
    8037: " Che bella sensazione di libertà totale!",
    8038: " Spero davvero di poterti abbracciare presto. Grazie di cuore per tutto quello che fai per me e per milioni di altri ragazzi invisibili.",
    8039: " Sta a noi giocare con moderazione e non perdere mai di vista i nostri grandi obiettivi nella vita di tutti i giorni. Usiamo la tecnologia, ma non facciamoci usare da essa.",
    8040: " E la cosa più bella fu che, amandosi finalmente per quello che era, scoprì di essere molto più forte e coraggiosa di quanto avesse mai immaginato nei suoi sogni migliori.",
    
    8041: " \\n\\nCon il passare dei mesi, Matteo si accorse che le cose stavano migliorando in modo significativo non solo a scuola, ma anche a casa. Quando il padre passava a prenderlo per il fine settimana, invece di chiudersi in un mutismo ostinato e rancoroso, Matteo provava ad aprirsi, spiegando come si sentiva e cosa gli mancava della vecchia vita familiare. Con sua grande sorpresa, anche il padre, solitamente chiuso ed estremamente severo, cominciò a piangere e ad ammettere i propri errori, chiedendo scusa per non essere stato abbastanza presente negli ultimi anni difficili. Quelle lunghe e dolorose conversazioni intime aiutarono entrambi a ricostruire un rapporto nuovo, più maturo, vero e profondo, basato su una comunicazione autentica e senza inutili difese artificiali.\\n\\nAlla fine del difficile anno scolastico, Matteo decise di scrivere una lunga lettera aperta di ringraziamento da leggere davanti a tutta la classe. Quando arrivò il suo turno di parlare, si alzò in piedi e guardò i suoi compagni di classe con ritrovata sicurezza. Le sue mani non tremavano più, e la sua voce risuonava forte e cristallina nell'aula silenziosa. Ringraziò apertamente il professore per avergli teso una mano e i suoi nuovi compagni per averlo ascoltato senza mai giudicare le sue fragilità. In quel preciso e indimenticabile istante, il ragazzo capì in modo definitivo che il vero coraggio non consiste nel nascondere e reprimere le proprie emozioni dietro un muro di pietra per sembrare invincibili e freddi, ma nell'avere la grandissima forza di mostrarle agli altri per farsi aiutare e guarire le ferite del cuore.",
    
    8042: " \\n\\nCon l'arrivo dell'estate, la grande e solida amicizia tra Andrea e Youssef si rafforzò ancora di più, allargandosi in modo del tutto naturale anche alle loro rispettive famiglie, che fino a quel momento non si erano mai parlate. I genitori di Andrea decisero di invitare la famiglia di Youssef a trascorrere l'intero fine settimana estivo nella loro piccola ma accogliente casa in campagna, situata tra le verdi colline coltivate a ulivi e rigogliosi vigneti profumati. L'inizio fu un po' teso e imbarazzato a causa della barriera linguistica dei genitori, ma il clima cambiò in pochissimi minuti quando le due mamme, pur non conoscendo quasi nessuna parola in comune, si ritrovarono insieme nella grande cucina a preparare un banchetto multietnico mai visto prima d'allora.\\n\\nSulla lunghissima e bellissima tavolata imbandita sotto il portico di legno, il profumo intenso e inconfondibile della classica lasagna italiana al ragù si mescolò armoniosamente con il profumo pungente e speziato del cous cous di verdure e carne arrostita, mentre il dolce suono delle cicale estive accompagnava chiacchiere, risate spontanee e continui e affettuosi scambi di ricette tradizionali e antichi segreti culinari. Andrea e Youssef, seduti uno accanto all'altro sul prato appena tagliato, guardavano le loro famiglie chiacchierare serenamente in un mix buffo e simpatico di arabo, italiano e vivaci gesti con le mani. Questa bellissima immagine di assoluta fratellanza e convivenza pacifica, nata grazie a un banalissimo panino diviso a metà in un polveroso cortile di scuola, ricordò ancora una volta ai due giovani ragazzi una grandissima verità universale: la paura e l'ignoranza dividono, ma la generosità unisce e guarisce il mondo intero.",
    
    8043: " \\n\\nLa sera, dopo una lunga ed estenuante giornata di duro lavoro manuale per tagliare legna e riparare gli spessi tetti di paglia per proteggersi dalle fredde piogge, i contadini e i servitori del castello si ritrovavano abitualmente nella calda e fumosa taverna del villaggio fortificato. Lì, sorseggiando birra calda e mangiando pane nero raffermo con pezzi di formaggio salato, si scambiavano notizie preziose sui viandanti passati, raccontavano storie di fantasmi che si diceva infestassero le torri più alte del castello e condividevano le loro piccole e grandi preoccupazioni quotidiane. Spesso, queste riunioni notturne erano animate dalla presenza improvvisa di qualche menestrello viaggiatore di passaggio che cantava appassionanti poemi epici cavallereschi, accompagnandosi con le dolci e melodiose note del suo liuto di legno scuro.\\n\\nLa rigida struttura sociale non ammetteva eccezioni né sconti per nessuno: la nobildonna del castello passava le sue oziose giornate immersa in preghiere silenziose e faticosi lavori di ricamo vicino alle piccole finestre, mentre il povero contadino piegava la schiena nei campi infangati dall'alba al tramonto. Tuttavia, quando un pericolo mortale imminente si avvicinava minacciosamente ai confini del feudo, come un improvviso e sanguinoso assedio da parte di un feroce esercito nemico confinante o lo scoppio improvviso di una rapida pestilenza sconosciuta, tutte le barriere di classe e le differenze economiche crollavano istantaneamente. In quei momenti bui e catastrofici, nobili armati di scudi di ferro e contadini armati di falci e forconi si trovavano obbligatoriamente a combattere fianco a fianco, soffrendo la stessa paura opprimente e uniti dallo stesso istinto di protezione. Queste immense sfide dimostravano quanto la vera forza di quel freddo e imponente mondo medievale di pietra non risiedesse unicamente nello spessore inespugnabile delle altissime e possenti mura difensive, ma nel fondamentale spirito di comunità solidale e inossidabile di tutte quelle coraggiose persone.",
    
    8044: " \\n\\nUn anno e mezzo dopo l'eccezionale scoperta dei rarissimi batteri marziani primitivi nel sottosuolo roccioso della remota caverna, la colonia Marte Rosso si preparò a compiere un ulteriore e importantissimo balzo in avanti: l'arrivo tanto atteso della primissima vera e propria 'serra agricola esterna'. Questo innovativo e pionieristico progetto ingegneristico, guidato dalla determinata e geniale Elara, prevedeva l'utilizzo di enormi e speciali cupole polimeriche in grado di resistere ai violentissimi venti di sabbia corrosiva che spazzavano la desolata superficie del pianeta. Le cupole non avrebbero solo protetto le preziose colture dalle insidiose tempeste, ma avrebbero anche iniziato a produrre lentamente ingenti quantità di prezioso ossigeno puro tramite un complesso e silenziosissimo processo di fotosintesi artificiale, progettato per innescare un lentissimo ma inesorabile cambiamento benefico di tutta l'arida atmosfera marziana.\\n\\nIl giorno storico in cui i giganteschi robot automatizzati completarono la perfetta sigillatura dell'immenso modulo serra esterno, tutti i coraggiosi coloni, con il fiato sospeso per l'emozione incontrollabile, si radunarono silenziosi davanti alle enormi finestre di osservazione della loro piccola e affollata base principale. Al primo vero e proprio accenno di un intenso e caldo verde brillante che germogliava timidamente attraverso la spessa polvere rossa che ricopriva il terreno artificiale fertilizzato, ci fu un grandissimo e corale grido di esultanza incontenibile, accompagnato da lacrime di sincera gioia che rigaiono i volti provati degli scienziati spaziali. Vedere spuntare i primissimi minuscoli fili d'erba vitale su un gelido pianeta morto da moltissimi millenni non era solamente un clamoroso ed epocale trionfo scientifico dell'intera razza umana, ma rappresentava una profonda e commovente poesia visiva di rinascita totale, un simbolo universale e potente dell'indistruttibile determinazione dell'umanità nel portare e proteggere il fuoco inestimabile e sacro della vita anche negli abissi freddi, oscuri e inesplorati dello spazio infinito interstellare.",
    
    8045: " \\n\\nDopo la grande ed epica sconfitta finale del malvagio Re dell'Oblio e il crollo inesorabile del suo spaventoso Castello d'Ombra tra le nuvole arancioni neon di Antiriflessia, il mondo parallelo iniziò subito una rapidissima e magica rinascita senza precedenti storici. Le creature di Antiriflessia, che per moltissimi secoli avevano vissuto rassegnate nel terrore oscuro di veder rubati i loro ricordi più preziosi, uscirono finalmente e gioiosamente dai loro nascondigli nascosti. Le meravigliose farfalle parlanti con ali di vetro colorato intonarono dolcissime melodie di ringraziamento e gli enormi saggi gufi giganti previdero per il regno una lunghissima e luminosissima era di assoluta prosperità, amicizia profonda e pace duratura per tutti i popoli.\\n\\nElara, la coraggiosissima principessa dal cuore d'oro, sapeva bene che il suo faticoso e difficilissimo compito era stato brillantemente portato a termine. Prima di riattraversare tristemente ma orgogliosamente il magico e misterioso portale subacqueo luminoso per tornare nel suo amato mondo d'origine, salutò uno per uno tutti i suoi nuovi e inseparabili amici fantastici, promettendo solennemente che non avrebbe mai e poi mai dimenticato tutte le straordinarie e incredibili avventure vissute in quel magico regno alla rovescia. Quando la ragazza riemerse finalmente e silenziosamente dalle placide e calme acque cristalline del Grande Lago di Cristallo nel suo verdeggiante regno, notò subito qualcosa di completamente nuovo, inaspettato e bellissimo: il suo riflesso non era più malinconico e spaventato, ma sorrideva sinceramente con grandissima fiducia, riflettendo pienamente la sua enorme e immensa forza interiore finalmente scoperta e conquistata a duro prezzo.",
    
    8046: " \\n\\nQuesto grandissimo ed epocale traguardo personale rappresentò non solo la vera conclusione del mio difficilissimo e complicato percorso universitario formativo di studi superiori, ma anche il primissimo e importantissimo passo verso una nuova e luminosissima carriera professionale, in un mondo in cui saper esprimere in modo molto chiaro ed efficace le proprie brillanti idee e argomentazioni è diventato oggi a dir poco essenziale e irrinunciabile per poter ottenere il successo tanto agognato. Grazie all'importante corso di recitazione teatrale inaspettatamente seguito mesi prima e alla mia forte tenacia interiore e perseveranza assoluta, iniziai ben presto a ricevere moltissime offerte lavorative esaltanti, per condurre in prima persona importanti e delicati corsi di comunicazione strategica dedicati proprio agli studenti ansiosi che si trovavano ad affrontare quegli stessi identici incubi a me fin troppo familiari.\\n\\nQueste straordinarie e continue vittorie personali sul palco mi hanno insegnato una lezione fondamentale e validissima per ogni aspetto critico e problematico della nostra complicata vita moderna. Ognuno di noi ha le sue altissime montagne rocciose e fredde da dover necessariamente e faticosamente scalare ogni singolo giorno, che siano rappresentate da timidezze invalidanti, ansie sociali asfissianti o paure di non essere mai sufficientemente all'altezza delle fortissime aspettative esterne imposte dalla dura società. La fuga e l'isolamento completo sembrano sempre le soluzioni di comodo di gran lunga più facili e rassicuranti da adottare nell'immediato, ma affrontare il buio con enorme e sincero coraggio guardando la folla in faccia permette all'anima umana di fiorire, evolversi e rivelarsi prepotentemente a tutto il mondo nel suo vero e immenso splendore naturale.",
    
    8047: " \\n\\nOltre al suo enorme impegno incondizionato e instancabile nella ricerca e sperimentazione ingegneristica spaziale di più altissimo livello internazionale e alla sua importantissima e pregevole opera costante e assidua per la diffusione divulgativa della cultura e delle scienze moderne tra le giovani e promettenti generazioni di ragazze studentesse e sognatrici ad occhi aperti di tutto il globo terrestre, l'astronauta e pilota italiana Samantha Cristoforetti ha dimostrato con eccezionale e commovente umiltà, sincero affetto e grandissima umanità di non aver mai minimamente dimenticato i suoi piccoli e bellissimi luoghi natali, quelle meravigliose e spettacolari montagne alpine ricoperte di foreste e neve e quei lussureggianti e antichi boschi silenziosi del profondo Trentino che per primi, in tenera età, le avevano ispirato l'incanto viscerale per il cielo aperto, lo stupore per il grande spazio infinito notturno e l'irrefrenabile desiderio innato di esplorare nuovi e sconosciuti orizzonti lontani.\\n\\nIn un momento assai toccante e molto speciale, e per molti versi poetico e unico, durante un collegamento televisivo satellitare di alta qualità in diretta mondiale dalla famosissima e orbitante stazione spaziale internazionale ISS che le serviva per comunicare con la stampa planetaria, si è sinceramente emozionata nel rivedere dallo spazio e fotografare personalmente le amate vette altissime e appuntite delle splendide Dolomiti imbiancate e maestose illuminate dalla flebile e meravigliosa luce del primo mattino. Questa stupenda e indimenticabile immagine iconica ha sigillato in maniera permanente un fortissimo e magico legame emotivo eterno e indissolubile tra le solide e rassicuranti origini umane e montane e gli spinti traguardi scientifici moderni e tecnologici del nostro radioso futuro. Grazie e mille complimenti ancora a te, eroica e audace esploratrice instancabile del grandioso e immenso cosmo!",
    
    8048: " \\n\\nNei difficili, frenetici e turbolenti anni delle corse e lunghissime esplorazioni dell'astronomia che seguirono a brevissima distanza il primissimo, colossale e storico trionfo scientifico dell'allunaggio avvenuto il memorabile ed eccezionale 20 Luglio 1969 e mostrato a milioni di fortunati e sbalorditi telespettatori attoniti di ogni età ed estrazione in tutto l'intero globo terrestre in trepidante attesa globale, il fortissimo entusiasmo emotivo generato da quell'impresa colossale e pionieristica portò allo sviluppo prodigioso di importantissime innovazioni tecnologiche moderne. Tra queste spiccano formidabili sensori di precisone elettronica miniaturizzata, resistentissimi e nuovi materiali speciali e innovativi fondamentali strumenti ultra-resistenti leggeri progettati in esclusiva dall'ingegneria, di cui ancora oggi, in pieno ventunesimo secolo, ci avvaliamo costantemente in modo massiccio, intenso e molto pratico anche nella nostra normale, semplice e assai comoda e confortevole vita cittadina quotidiana di tutti i giorni moderni.\\n\\nMa al di là della fondamentale utilità pratica derivante dalle scoperte ingegneristiche continue e preziose, il formidabile e mastodontico sbarco spaziale umano lunare del coraggioso equipaggio interstellare della missione super complessa Apollo 11 ci ha donato un insegnamento molto più profondo, filosofico, estremamente importante e intimamente saggio. Il viaggio ci ha chiaramente ricordato che siamo solo piccoli esseri intelligenti sperduti e fragilissimi a bordo di una delicata e rarissima meravigliosa nave verde e azzurra che fluttua senza meta costante nel buio infinito e gelido del grandissimo e affascinante spazio cosmico insondabile. Questa fortissima consapevolezza unica, rara e spaventosa impone in modo forte e perentorio a tutte le donne e uomini la profonda e imprescindibile necessità umana e morale di riuscire a custodire molto meglio la pace terrestre assoluta, e difendere in modo più serio l'ambiente vitale della nostra comune e preziosissima, grande casa."
}

def expand_texts():
    global content
    for id_val, addition in additions.items():
        pattern = r'("id": ' + str(id_val) + r',.*?"text": ")(.*?)(")'
        match = re.search(pattern, content, re.DOTALL)
        if match:
            old_text = match.group(2)
            new_text = old_text + addition
            full_old = match.group(0)
            full_new = match.group(1) + new_text + match.group(3)
            content = content.replace(full_old, full_new)
        else:
            print(f"Could not find ID {id_val}")
            
expand_texts()

with open('js/exercises.js', 'w', encoding='utf-8') as f:
    f.write(content)
print("Updated texts successfully.")
