import re

with open('js/exercises.js', 'r', encoding='utf-8') as f:
    content = f.read()

additions = {}

# 8025: Il lupo tecnologico e l'agnello furbo (Favola, Intermedio) - current 335 -> needs 300
additions[8025] = " \\n\\nIl lupo, frustrato, decise allora di utilizzare un drone silenzioso dotato di telecamera a infrarossi per scovare il nascondiglio dell'agnello senza doversi alzare dal divano. 'Questa volta non mi scappi!', sghignazzò, guardando lo schermo del suo tablet. Ma l'agnello, che aveva letto molti libri sulla tecnologia, aveva costruito un piccolo dispositivo di interferenza magnetica usando vecchie lattine e fili di rame. Appena il drone si avvicinò alla sua tana, il segnale fu disturbato, e l'apparecchio finì per schiantarsi miseramente contro un grande albero di quercia, andando in mille pezzi.\\n\\nIl lupo era su tutte le furie. 'Non è possibile che un agnellino senza Wi-Fi possa sconfiggermi!', gridò. Decise di usare l'arma finale: un cyber-trappolone olografico che proiettava l'immagine di un prato verdissimo e invitante, in grado di ingannare chiunque. Posizionò la trappola vicino al ruscello e si nascose dietro un cespuglio. L'agnello, vedendo l'erba finta, si avvicinò con calma. Invece di caderci dentro, però, tirò fuori il suo vecchio specchietto da tasca e lo usò per riflettere un raggio di sole dritto nel sensore ottico dell'ologramma, che andò in cortocircuito emettendo scintille e fumo grigio.\\n\\nIl lupo, spaventato dal fumo, scappò via a gambe levate, inciampando nei suoi stessi cavi di ricarica. L'agnello tornò sereno al suo ruscello, accendendo un fuoco per scaldarsi. Aveva dimostrato a tutti gli animali del bosco che i gadget tecnologici, per quanto avanzati, non potranno mai sostituire l'ingegno, la vera intelligenza e il buon senso. Da quel giorno, il lupo smise di comprare apparecchi elettronici e tornò a studiare i vecchi metodi tradizionali, ma l'agnello rimase sempre e comunque un passo avanti a lui."

# 8026: Il principe e il drago di ghiaccio (Fiaba, Intermedio) - current 352 -> needs 300
additions[8026] = " \\n\\nDurante il lungo cammino verso la Montagna di Cristallo, il giovane principe incontrò numerosi ostacoli. Prima dovette attraversare la 'Foresta dei Sussurri Congelati', dove gli alberi erano completamente ricoperti di brina e le foglie scricchiolavano come vetro rotto sotto i suoi stivali. In questa foresta, incontrò una vecchia volpe delle nevi intrappolata sotto un ramo caduto. Nonostante la fretta e il freddo pungente, Enea si fermò e usò tutta la sua forza per liberare l'animale. La volpe, grata per il nobile gesto, gli donò una piccola gemma azzurra. 'Questa pietra', disse la volpe, 'ti proteggerà dal respiro letale del drago'.\\n\\nProseguendo, Enea giunse finalmente ai piedi della montagna. La salita era ripida e scivolosa. Il vento gelido cercava di spingerlo giù, ma la forza del suo cuore lo spingeva a continuare. Quando raggiunse la cima, si trovò di fronte a una gigantesca caverna formata da enormi stalattiti di ghiaccio. Al centro della caverna, illuminato da una debole luce azzurrina, riposava il possente drago. Le sue scaglie brillavano come diamanti taglienti e i suoi occhi ricordavano profondi laghi ghiacciati.\\n\\nInvece di estrarre la spada, Enea si ricordò delle parole del saggio. Alzò in aria il medaglione d'oro. Il drago si svegliò, aprendo le fauci per emettere il suo respiro congelante, ma la gemma della volpe creò una barriera invisibile che protesse il principe. Il calore del medaglione iniziò a sciogliere il ghiaccio attorno al cuore del drago, rivelando un piccolo frammento scuro, una maledizione che un mago malvagio aveva lanciato molto tempo prima. Con il potere dell'amore per la sua famiglia, Enea distrusse il frammento. Il drago, finalmente libero dal dolore, ruggì di gioia e restituì il sole al regno, giurando eterna amicizia al valoroso principe."

# 8027: La spada di cristallo e l'Ombra (Fantasy, Intermedio) - current 282 -> needs 350
additions[8027] = " \\n\\nPer superare il Lago, Aria e Kael dovettero affrontare il primo dei tre guardiani: un colossale serpente d'acqua le cui scaglie brillavano di una luce verdastra e sinistra. Aria, ricordando gli antichi canti della sua famiglia, iniziò a intonare una melodia lenta e armoniosa. La magia della sua voce calmò l'ira del serpente, che invece di attaccarli, si offrì di trasportarli sulla sua schiena squamosa fino all'altra sponda. Fu un viaggio terrificante ma affascinante, in cui videro rovine sommerse di civiltà dimenticate che giacevano sul fondo del lago oscuro.\\n\\nUna volta raggiunte le Montagne di Fuoco, il caldo divenne quasi insopportabile. Il terreno sotto i loro piedi fumava e i fiumi di lava tracciavano percorsi luminosi nella notte. Qui incontrarono il secondo guardiano: un golem di pietra vulcanica. Kael sapeva che le armi normali sarebbero state inutili contro la roccia. Usando la sua astuzia, corse intorno al golem, facendogli perdere l'equilibrio e spingendolo in una pozza di fango ribollente che ne bloccò i movimenti, permettendo ai due eroi di proseguire indenni verso la caverna più alta.\\n\\nFu proprio in quella caverna che trovarono finalmente la Spada di Cristallo. L'arma era conficcata in un piedistallo di quarzo purissimo e brillava di una luce bianca accecante, capace di dissipare qualsiasi oscurità. Ma prima che Aria potesse afferrarla, l'Oscuro Signore in persona, avvolto in un mantello di nebbia nera, si manifestò davanti a loro. Con un sorriso crudele, cercò di corrompere l'anima di Aria offrendole potere assoluto in cambio della resa. Aria rifiutò con forza e, sorretta dall'amore per il suo villaggio e dalla fedeltà di Kael, estrasse la spada. Un raggio di luce purissima travolse il Signore Oscuro, polverizzando lui e le sue ombre per sempre. L'equilibrio fu ristabilito e Luminaria tornò a splendere, eterna e meravigliosa."

# 8028: Sopravvissuti nella foresta amazzonica (Avventura, Intermedio) - current 258 -> needs 350
additions[8028] = " \\n\\nIl secondo giorno nella giungla fu ancora più difficile. La fame cominciava a farsi sentire, e le uniche cose commestibili che i ragazzi riuscirono a trovare furono alcune bacche rosse, che Diego, fortunatamente, aveva studiato in un libro di botanica e sapeva non essere velenose. Durante la ricerca del cibo, Sofia si accorse di essere seguita da un grosso giaguaro. Il felino si muoveva silenziosamente tra i rami, scrutandoli con occhi gialli e famelici. Mantenendo la calma, Sofia suggerì a Diego di non correre per non attivare l'istinto predatorio dell'animale. Insieme, iniziarono a fare molto rumore sbattendo due grossi bastoni contro un tronco cavo e gridando a squarciagola. Il giaguaro, infastidito dal frastuono insolito, si girò e scomparve lentamente nel fitto della vegetazione verde scuro.\\n\\nLa terza notte fu caratterizzata da una tempesta tropicale violenta. L'acqua cadeva come una cascata, spegnendo il fuoco che avevano fatto tanta fatica ad accendere sfregando legnetti secchi. Furono costretti a rifugiarsi sotto le radici enormi di un albero secolare, abbracciati per farsi coraggio, mentre i tuoni facevano tremare la terra sotto di loro. Proprio in quella notte di terrore, Diego notò un dettaglio fondamentale: la direzione in cui scorreva l'acqua piovana. Seguendo il piccolo ruscello temporaneo creato dal temporale, i due giovani capirono che prima o poi l'acqua li avrebbe condotti a un fiume più grande.\\n\\nLa mattina successiva, seguendo il corso d'acqua, giunsero finalmente sulle sponde del grande Rio delle Amazzoni. Lì, esausti e ricoperti di fango, videro un piccolo battello di pescatori locali. Sventolando la giacca rossa di Sofia, riuscirono ad attirare l'attenzione dei marinai. Furono salvati e riportati alla civiltà. Quella straordinaria e terribile avventura insegnò loro che il vero coraggio non sta nel non avere paura, ma nel non arrendersi mai, e che la natura, sebbene possa essere crudele e spietata, offre sempre una via di salvezza a chi sa ascoltarla."

# 8029: Regolamento ufficiale del gioco degli scacchi (Testo regolativo, Intermedio) - current 256 -> needs 350
additions[8029] = " \\n\\nUna regola molto importante e particolare degli scacchi è l'**arrocco**. Questa mossa speciale si può eseguire una sola volta durante la partita e coinvolge il re e una delle torri. Per arroccare, il re deve muoversi di due case verso la torre, e la torre salta sopra il re posizionandosi nella casa adiacente. L'arrocco è utile per mettere il re al sicuro e sviluppare la torre verso il centro, ma attenzione: non si può arroccare se il re o la torre sono già stati mossi in precedenza, né se il re si trova sotto scacco.\\n\\nUn'altra mossa speciale riguarda i pedoni ed è chiamata **'en passant'** (presa al varco). Se un pedone avversario avanza di due case dal suo punto di partenza e si affianca a un tuo pedone, puoi catturarlo come se fosse avanzato di una sola casa, ma devi farlo immediatamente alla mossa successiva, altrimenti perdi questo diritto speciale.\\n\\nInoltre, se un pedone coraggioso riesce ad attraversare tutta la scacchiera e raggiungere l'ultima traversa opposta, si verifica la **promozione**. Il pedone viene immediatamente sostituito con un'altra figura a scelta dello stesso colore (solitamente si sceglie la Donna, poiché è il pezzo più potente, ma si può scegliere anche Cavallo, Alfiere o Torre). Questo significa che è possibile avere contemporaneamente più di una Donna sulla scacchiera!\\n\\nInfine, una partita non si vince solo dando scacco matto. Si può verificare anche il **pareggio** (patta), che avviene in diverse situazioni: quando sulla scacchiera rimangono troppi pochi pezzi per dare scacco matto (ad esempio, solo i due re), quando la stessa posizione si ripete esattamente per tre volte, oppure quando un giocatore non è sotto scacco ma non ha alcuna mossa legale a disposizione (situazione chiamata 'stallo'). Rispettare queste regole è essenziale per godersi appieno la bellezza di questo antico gioco."

# 8030: Il mondo affascinante dei Dinosauri (Testo espositivo, Intermedio) - current 221 -> needs 400
additions[8030] = " \\n\\nUno degli aspetti più affascinanti dello studio dei dinosauri è la loro incredibile diversità di dimensioni e forme. Alcuni, come l'Argentinosauro, erano colossi che potevano raggiungere i 35 metri di lunghezza e pesare decine di tonnellate; avevano lunghi colli per nutrirsi delle foglie più alte degli alberi e si muovevano in grandi branchi per proteggersi dai predatori. Altri, come il Compsognathus, erano piccoli quanto un pollo moderno, agilissimi e veloci, specializzati nella caccia a piccoli insetti e lucertole nel fitto del sottobosco preistorico.\\n\\n### Il re dei predatori: Il Tyrannosaurus Rex\nTra i dinosauri carnivori (i teropodi), il più famoso e temuto era senza dubbio il Tyrannosaurus Rex. Vissuto circa 68 milioni di anni fa nel periodo Cretaceo, questo super-predatore poteva superare i 12 metri di lunghezza e aveva un cranio enorme dotato di mascelle potentissime. I suoi denti seghettati potevano frantumare ossa con facilità. Nonostante avesse braccia anteriori sorprendentemente corte e apparentemente inutili, le sue potenti zampe posteriori gli permettevano di correre a grandi velocità per brevi distanze. Recenti studi suggeriscono che il T-Rex potesse anche essere un animale spazzino, che si nutriva di carcasse di animali già morti.\\n\\n### I dinosauri piumati e l'origine degli uccelli\nPer molto tempo si è pensato che i dinosauri fossero creature lente e coperte di squame come le lucertole attuali. Tuttavia, straordinarie scoperte fossili in Cina hanno rivoluzionato questa idea. È stato dimostrato che molti dinosauri carnivori, inclusi i velociraptor, erano ricoperti di penne e piume colorate. Queste piume inizialmente non servivano per volare, ma per mantenere costante la temperatura corporea o per attirare i partner durante i rituali di accoppiamento. Oggi gli scienziati sono concordi nell'affermare che gli uccelli moderni, dai piccoli passeri alle grandi aquile, sono in realtà i diretti discendenti di un gruppo di piccoli dinosauri teropodi sopravvissuti alla grande estinzione.\\n\\nLa paleontologia, la scienza che studia i fossili, continua a regalarci nuove scoperte ogni anno, aiutandoci a ricostruire un passato remoto e meraviglioso in cui la Terra era un pianeta selvaggio dominato dai giganti più straordinari che siano mai esistiti."

# 8031: La mia città del cuore: Firenze (Descrizione, Intermedio) - current 252 -> needs 350
additions[8031] = " \\n\\nAttraversando il fiume Arno, si deve passeggiare sul famoso Ponte Vecchio, un luogo magico sospeso sull'acqua, fiancheggiato da storiche e luccicanti botteghe di orafi e gioiellieri. Sopra i tetti di queste botteghe passa il Corridoio Vasariano, un passaggio segreto che i granduchi usavano per spostarsi senza scendere in strada. La luce del tramonto che si riflette sulle acque calme dell'Arno e sulle case color ocra del ponte crea un'atmosfera così romantica e suggestiva da sembrare un dipinto.\\n\\nNon si può visitare Firenze senza esplorare Piazza della Signoria, un vero e proprio museo a cielo aperto. Qui si erge imponente Palazzo Vecchio, con la sua alta torre merlata, e la Loggia dei Lanzi, che ospita sculture straordinarie come il Perseo con la testa di Medusa. Tra queste piazze e i vicoli stretti, si respira ancora l'aria del Rinascimento italiano, epoca in cui geni immensi come Leonardo da Vinci, Michelangelo e Botticelli passeggiavano e discutevano d'arte proprio su questi ciottoli sconnessi.\\n\\nMa Firenze non è solo arte antica; è anche profumi inebrianti e sapori forti. Nei mercati rionali, come quello di San Lorenzo, i banchi colorati offrono prodotti freschi e deliziosi della campagna toscana. Fermarsi a gustare un panino con il lampredotto caldo o una generosa bistecca alla fiorentina è un'esperienza sensoriale irrinunciabile. I fiorentini, con il loro accento inconfondibile e la loro battuta sempre pronta, accolgono i visitatori con una ruvida ma sincera simpatia.\\n\\nQuando cala la sera, la città si illumina di una luce calda e avvolgente. Salire al Piazzale Michelangelo al crepuscolo permette di ammirare l'intero panorama di Firenze dall'alto, con i tetti rossi, le cupole e i campanili che si stagliano contro il cielo stellato. È in questi momenti di assoluta bellezza che si capisce perché Firenze non è solo una città, ma una vera e propria capitale eterna del cuore umano."

# 8032: La magia della Poesia: L'Infinito (Poesia, Intermedio) - current 173 -> needs 450
additions[8032] = " \\n\\nQuesto colle, probabilmente il Monte Tabor vicino a Recanati, è un luogo reale che si trasforma in uno spazio dell'anima. La siepe, un ostacolo fisico e naturale, diventa paradossalmente lo strumento principale che scatena l'immaginazione del giovane poeta. Proprio perché la vista materiale è impedita dalle foglie fitte della pianta, la mente è costretta ad andare 'oltre', a figurarsi mondi lontani e spazi senza alcun confine umano.\\n\\nNel secondo momento della poesia, un elemento uditivo interviene a risvegliare Leopardi dal suo viaggio immaginario: è il suono del vento che fruscia tra le foglie delle piante circostanti. Questo piccolo e fragile suono naturale, così vicino e presente, viene immediatamente paragonato dal poeta al concetto di infinito e all'eternità del tempo. Leopardi paragona il passato, ormai morto e lontano ('le morte stagioni'), al presente vivo e rumoroso ('la presente e viva, e il suon di lei').\\n\\nIn questo vertiginoso confronto tra la finitezza umana, la fragilità della natura e l'immensità cosmica dell'universo, l'anima del poeta si abbandona completamente. L'ultimo verso ('E il naufragar m'è dolce in questo mare') esprime una sensazione di totale e dolce smarrimento. Il naufragio, che solitamente è un evento drammatico e mortale per i marinai, qui diventa un'esperienza positiva e catartica: perdere la propria razionalità e abbandonarsi ai sentimenti più profondi genera una pace assoluta e misteriosa.\\n\\n'L'Infinito' non è solo un componimento tecnico di straordinaria fattura, scritto in endecasillabi sciolti senza rime obbligate, ma è un vero e proprio manifesto della condizione umana. Ci insegna che ognuno di noi, anche quando si sente chiuso e limitato nella propria piccola realtà quotidiana o dietro una 'siepe' di problemi, possiede la capacità incredibile di viaggiare con la fantasia e di sfiorare l'assoluto con la propria intelligenza emotiva."

def expand_texts():
    global content
    for id_val, addition in additions.items():
        pattern = r'("id": ' + str(id_val) + r',.*?"text": ")(.*?)(")'
        match = re.search(pattern, content, re.DOTALL)
        if match:
            old_text = match.group(2)
            new_text = old_text + addition
            full_old = match.group(0)
            full_new = match.group(1) + new_text + match.group(3)
            content = content.replace(full_old, full_new)
        else:
            print(f"Could not find ID {id_val}")
            
expand_texts()

with open('js/exercises.js', 'w', encoding='utf-8') as f:
    f.write(content)
print("Updated texts successfully.")
