import re

with open('js/exercises.js', 'r', encoding='utf-8') as f:
    content = f.read()

additions = {
    8014: " Spero di ricevere la tua lettera al più presto con tante belle notizie. Ciao amico mio!",
    8015: " Non dimentichiamoci mai che muoversi e sudare significa vivere pienamente e crescere sani e forti in ogni momento della nostra fantastica giovinezza.",
    8019: " Le gesta dei gladiatori e la maestosità dell'anfiteatro rimasero per sempre impresse nella sua mente e nel suo cuore valoroso di giovane romano.",
}

# 8020: Avventura nell'anno 3000 (Fantascienza, Facile) - current 240 -> needs 370
additions[8020] = " \\n\\nIl loro viaggio galattico era appena iniziato. La loro astronave, chiamata 'Stella Cadente', era dotata di motori a propulsione quantistica che permettevano di viaggiare alla velocità della luce. All'interno, tutto era bianco e pulitissimo. C'erano giardini idroponici dove crescevano pomodori quadrati e mele blu, perfette per i lunghi viaggi nello spazio profondo. Il robot Z-99 non solo preparava i pasti, ma raccontava anche vecchie barzellette della Terra per tenere alto il morale dell'equipaggio.\\n\\nUn giorno, mentre attraversavano la nebulosa di Orione, i sensori della nave segnalarono un segnale di SOS. Veniva da un piccolo pianeta roccioso mai esplorato prima, circondato da tre lune viola. Kira e Z-99 decisero di scendere con una navicella di salvataggio per investigare. Quando atterrarono, scoprirono una base scientifica abbandonata, coperta di una strana polvere luccicante. All'interno, trovarono uno scienziato alieno intrappolato sotto una pesante lastra di metallo. Lo scienziato, che aveva la pelle verde e quattro braccia, ringraziò Kira per averlo salvato.\\n\\nPer sdebitarsi, l'alieno regalò a Kira una mappa stellare olografica che mostrava la posizione di una leggendaria galassia di puro cristallo, un luogo magico che tutti credevano fosse solo un mito. Entusiasta per la nuova scoperta, Kira tornò sulla 'Stella Cadente' e inserì le nuove coordinate nel computer di bordo. L'astronave partì a tutta velocità verso l'ignoto, pronta per nuove e incredibili avventure tra le stelle."

# 8021: Il paese dove tutto è possibile (Fantastico, Facile) - current 269 -> needs 350
additions[8021] = " \\n\\nUn pomeriggio, mentre passeggiava nel bosco di zucchero filato, Sofia incontrò un simpatico scoiattolo con il pelo a pois azzurri. Lo scoiattolo le spiegò che il re del paese, il Grande Orologiaio Magico, aveva perso la sua chiave d'oro e non poteva più caricare l'orologio della felicità. Se l'orologio si fosse fermato, il paese sarebbe scomparso per sempre!\\n\\nSofia, che era una bambina molto coraggiosa, decise di aiutare il re. Attraversò il fiume di limonata usando una barchetta fatta di biscotti e scalò la montagna di panna montata, sfidando un forte vento freddo al sapore di menta. In cima alla montagna, trovò un vecchio drago addormentato che russava così forte da far tremare la terra. La chiave d'oro era proprio lì, appesa al collo del drago!\\n\\nCon molta attenzione, Sofia si avvicinò in punta di piedi. Riuscì a sfilare la chiave senza svegliare la grossa creatura e corse giù dalla montagna il più velocemente possibile. Quando consegnò la chiave al re, l'intero paese fece una grande festa. I fiori cantarono canzoni di gioia e piovvero caramelle dal cielo. Il re ringraziò Sofia e le regalò un piccolo orologio da taschino: ogni volta che voleva, bastava premerlo per tornare nel paese magico e vivere nuove, dolcissime avventure."

# 8022: I ricordi della mia infanzia (Autobiografia, Facile) - current 213 -> needs 400
additions[8022] = " \\n\\nRicordo benissimo la mia vecchia bicicletta rossa. Aveva il campanello arrugginito e le ruote un po' sgonfie, ma per me era come un cavallo magico. Ci passavo ore intere a pedalare su e giù per la strada polverosa vicino a casa, immaginando di essere un grande esploratore in terre sconosciute. Un giorno, mentre cercavo di fare una discesa senza tenere le mani sul manubrio, persi l'equilibrio e caddi rovinosamente a terra, sbucciandomi entrambe le ginocchia. Piangevo disperato, ma la nonna mi prese in braccio, mi pulì le ferite e mi diede un grande pezzo di torta di mele appena sfornata. Il dolore sparì in un attimo, sostituito dal profumo dolce e rassicurante della cannella.\\n\\nUn altro ricordo indelebile è legato alle estati passate in campagna. Lì non c'erano videogiochi o televisione. Il divertimento consisteva nell'arrampicarsi sugli alberi più alti per raccogliere le ciliegie, nascondersi tra le balle di fieno e cercare di catturare le rane nello stagno dietro casa. La sera, io e i miei cugini ci sdraiavamo sul prato a guardare le stelle, inventando storie incredibili su alieni e pianeti lontani. A volte riuscivamo a vedere delle stelle cadenti e tutti chiudevamo gli occhi per esprimere un desiderio silenzioso.\\n\\nCrescendo, la vita diventa più complicata e frenetica, piena di impegni e responsabilità. Ma quando mi sento triste o stressato, mi basta chiudere gli occhi e tornare con la mente a quei giorni felici. I ricordi dell'infanzia sono come un tesoro prezioso custodito nel cuore, un rifugio sicuro dove poter ritrovare sempre un po' di pace e quella bellissima sensazione di spensieratezza e magia."

# 8023: Margherita Hack: la signora delle stelle (Biografia, Facile) - current 208 -> needs 400
additions[8023] = " \\n\\nNata a Firenze, Margherita dimostrò fin da piccola una grande curiosità e una mente brillante. Non amava giocare con le bambole, ma preferiva smontare orologi e capire come funzionassero le cose. Era anche una grande sportiva: da giovane fu una campionessa di salto in alto e salto in lungo. Questa sua energia e determinazione la aiutarono molto anche nello studio.\\n\\nAll'università, decise di studiare fisica in un periodo storico in cui pochissime donne sceglievano materie scientifiche. Nonostante le difficoltà e i pregiudizi, Margherita non si arrese mai. Dopo la laurea, iniziò a lavorare nei più importanti osservatori astronomici italiani, fino a diventare la prima donna a dirigere l'Osservatorio Astronomico di Trieste.\\n\\nIl suo lavoro principale consisteva nello studiare lo 'spettro' delle stelle, ovvero analizzare la luce che esse emettono per capire di quali elementi chimici sono composte. Grazie alle sue ricerche, oggi sappiamo molto di più sull'età e sulla nascita delle galassie. Ma Margherita non era solo una scienziata chiusa in laboratorio. Era famosa per la sua capacità di spiegare concetti difficilissimi in modo semplice e divertente, usando un linguaggio chiaro adatto a tutti, anche ai bambini.\\n\\nHa scritto tantissimi libri divulgativi ed è comparsa in numerosi programmi televisivi, diventando un volto noto e amato da tutti gli italiani. Era anche una convinta animalista: viveva circondata da gatti e cani randagi che aveva salvato dalla strada e difendeva a gran voce i diritti degli animali. Margherita ci ha insegnato che la scienza non è noiosa, ma è una grandissima avventura del pensiero, e che ognuno di noi, alzando gli occhi al cielo stellato, può sognare in grande."

# 8024: 20 Luglio 1969: L'uomo sbarca sulla Luna (Cronaca, Facile) - current 206 -> needs 400
additions[8024] = " \\n\\nIl viaggio della navicella spaziale Apollo 11 era iniziato quattro giorni prima, quando un gigantesco razzo, il Saturn V, era decollato dalla base di Cape Canaveral in Florida. A bordo c'erano tre coraggiosi astronauti: Neil Armstrong, Buzz Aldrin e Michael Collins. Il viaggio verso la Luna fu lungo e pieno di pericoli. Gli astronauti dovevano affrontare l'assenza di gravità, mangiare cibo disidratato da piccoli sacchetti di plastica e dormire legati ai loro sedili per non fluttuare in giro per la cabina.\\n\\nQuando finalmente raggiunsero l'orbita lunare, Armstrong e Aldrin si spostarono in un piccolo modulo chiamato 'Eagle' (Aquila) per scendere sulla superficie, mentre Collins rimase sull'astronave principale ad aspettarli girando intorno alla Luna. La discesa dell'Aquila fu un momento di grandissima tensione: il computer di bordo andò in allarme e il carburante stava per finire. Neil Armstrong dovette prendere i comandi manuali e cercare velocemente un punto piatto e sicuro dove atterrare, evitando enormi crateri e grossi massi di roccia spaziale.\\n\\nFinalmente, la radio gracchiò e si sentì la voce calma di Armstrong: 'Houston, qui Base della Tranquillità. L'Aquila è atterrata'. Sulla Terra scoppiò un applauso liberatorio in tutte le sale di controllo. Poche ore dopo, Armstrong aprì il portellone e scese lentamente la scaletta, seguito da Aldrin. I due astronauti piantarono la bandiera americana e raccolsero molti sassi lunari da portare agli scienziati per essere studiati.\\n\\nLasciavano sulla polvere grigia della Luna le loro impronte, destinate a rimanere intatte per milioni di anni perché lassù non c'è vento né pioggia. Quell'evento storico dimostrò che, lavorando insieme, l'umanità può superare ogni limite e realizzare sogni che sembravano impossibili. Fu davvero un grande giorno per tutta la Terra."

def expand_texts():
    global content
    for id_val, addition in additions.items():
        pattern = r'("id": ' + str(id_val) + r',.*?"text": ")(.*?)(")'
        match = re.search(pattern, content, re.DOTALL)
        if match:
            old_text = match.group(2)
            new_text = old_text + addition
            full_old = match.group(0)
            full_new = match.group(1) + new_text + match.group(3)
            content = content.replace(full_old, full_new)
        else:
            print(f"Could not find ID {id_val}")
            
expand_texts()

with open('js/exercises.js', 'w', encoding='utf-8') as f:
    f.write(content)
print("Updated texts successfully.")
